language: c

sudo: true

os:
  - linux
  - osx

compiler:
  - gcc
  - clang
  
script:
  - cd tnm
  - autoreconf -vi
  - if [ -f /usr/local/opt/tcl-tk/lib/tclConfig.sh ]; then ./configure --with-tcl=/usr/local/opt/tcl-tk/lib --prefix=/usr/local; else ./configure; fi
  - make
  - sudo make install
  - sudo make sinstall
